// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addConversationMember = `-- name: AddConversationMember :exec
INSERT INTO conversation_members (conversation_id, user_id, pet_id)
VALUES ($1, $2, $3)
ON CONFLICT (conversation_id, user_id) DO NOTHING
`

type AddConversationMemberParams struct {
	ConversationID string        `json:"conversation_id"`
	UserID         string        `json:"user_id"`
	PetID          uuid.NullUUID `json:"pet_id"`
}

func (q *Queries) AddConversationMember(ctx context.Context, arg AddConversationMemberParams) error {
	_, err := q.db.ExecContext(ctx, addConversationMember, arg.ConversationID, arg.UserID, arg.PetID)
	return err
}

const countConversationMessages = `-- name: CountConversationMessages :one
SELECT COUNT(*) FROM messages WHERE conversation_id = $1
`

func (q *Queries) CountConversationMessages(ctx context.Context, conversationID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConversationMessages, conversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMessages = `-- name: CountMessages :one
SELECT COUNT(*) FROM messages
`

func (q *Queries) CountMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserConversations = `-- name: CountUserConversations :one
SELECT COUNT(DISTINCT c.id) FROM conversations c
JOIN conversation_members cm ON c.id = cm.conversation_id
WHERE cm.user_id = $1
`

func (q *Queries) CountUserConversations(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserConversations, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (type, name, event_id)
VALUES ($1, $2, $3)
RETURNING id, type, name, event_id, created_at, updated_at
`

type CreateConversationParams struct {
	Type    string         `json:"type"`
	Name    sql.NullString `json:"name"`
	EventID uuid.NullUUID  `json:"event_id"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, createConversation, arg.Type, arg.Name, arg.EventID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.EventID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (conversation_id, sender_id, type, content)
VALUES ($1, $2, $3, $4)
RETURNING id, conversation_id, sender_id, type, content, created_at
`

type CreateMessageParams struct {
	ConversationID string `json:"conversation_id"`
	SenderID       string `json:"sender_id"`
	Type           string `json:"type"`
	Content        string `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ConversationID,
		arg.SenderID,
		arg.Type,
		arg.Content,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Type,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, type, name, event_id, created_at, updated_at FROM conversations WHERE id = $1
`

func (q *Queries) GetConversationByID(ctx context.Context, id string) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationByID, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.EventID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationMembers = `-- name: GetConversationMembers :many
SELECT cm.conversation_id, cm.user_id, cm.pet_id, cm.joined_at, cm.last_read_at, u.first_name, u.last_name, u.avatar_url as user_avatar,
       p.name as pet_name, p.avatar_url as pet_avatar
FROM conversation_members cm
JOIN users u ON cm.user_id = u.id
LEFT JOIN pets p ON cm.pet_id = p.id
WHERE cm.conversation_id = $1
`

type GetConversationMembersRow struct {
	ConversationID string         `json:"conversation_id"`
	UserID         string         `json:"user_id"`
	PetID          uuid.NullUUID  `json:"pet_id"`
	JoinedAt       time.Time      `json:"joined_at"`
	LastReadAt     sql.NullTime   `json:"last_read_at"`
	FirstName      string         `json:"first_name"`
	LastName       string         `json:"last_name"`
	UserAvatar     sql.NullString `json:"user_avatar"`
	PetName        sql.NullString `json:"pet_name"`
	PetAvatar      sql.NullString `json:"pet_avatar"`
}

func (q *Queries) GetConversationMembers(ctx context.Context, conversationID string) ([]GetConversationMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getConversationMembers, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetConversationMembersRow{}
	for rows.Next() {
		var i GetConversationMembersRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.UserID,
			&i.PetID,
			&i.JoinedAt,
			&i.LastReadAt,
			&i.FirstName,
			&i.LastName,
			&i.UserAvatar,
			&i.PetName,
			&i.PetAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDMConversation = `-- name: GetDMConversation :one
SELECT c.id, c.type, c.name, c.event_id, c.created_at, c.updated_at FROM conversations c
JOIN conversation_members cm1 ON c.id = cm1.conversation_id
JOIN conversation_members cm2 ON c.id = cm2.conversation_id
WHERE c.type = 'dm' AND cm1.user_id = $1 AND cm2.user_id = $2
LIMIT 1
`

type GetDMConversationParams struct {
	UserID   string `json:"user_id"`
	UserID_2 string `json:"user_id_2"`
}

func (q *Queries) GetDMConversation(ctx context.Context, arg GetDMConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getDMConversation, arg.UserID, arg.UserID_2)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.EventID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnreadCount = `-- name: GetUnreadCount :one
SELECT COUNT(*) FROM messages m
WHERE m.conversation_id = $1
  AND m.sender_id != $2
  AND m.created_at > COALESCE(
    (SELECT last_read_at FROM conversation_members WHERE conversation_id = $1 AND user_id = $2),
    '1970-01-01'::timestamptz
  )
`

type GetUnreadCountParams struct {
	ConversationID string `json:"conversation_id"`
	SenderID       string `json:"sender_id"`
}

func (q *Queries) GetUnreadCount(ctx context.Context, arg GetUnreadCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUnreadCount, arg.ConversationID, arg.SenderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const isConversationMember = `-- name: IsConversationMember :one
SELECT EXISTS(SELECT 1 FROM conversation_members WHERE conversation_id = $1 AND user_id = $2)
`

type IsConversationMemberParams struct {
	ConversationID string `json:"conversation_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) IsConversationMember(ctx context.Context, arg IsConversationMemberParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isConversationMember, arg.ConversationID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listMessages = `-- name: ListMessages :many
SELECT m.id, m.conversation_id, m.sender_id, m.type, m.content, m.created_at, u.first_name, u.last_name, u.avatar_url as sender_avatar
FROM messages m
JOIN users u ON m.sender_id = u.id
WHERE m.conversation_id = $1
ORDER BY m.created_at ASC
LIMIT $2 OFFSET $3
`

type ListMessagesParams struct {
	ConversationID string `json:"conversation_id"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

type ListMessagesRow struct {
	ID             string         `json:"id"`
	ConversationID string         `json:"conversation_id"`
	SenderID       string         `json:"sender_id"`
	Type           string         `json:"type"`
	Content        string         `json:"content"`
	CreatedAt      time.Time      `json:"created_at"`
	FirstName      string         `json:"first_name"`
	LastName       string         `json:"last_name"`
	SenderAvatar   sql.NullString `json:"sender_avatar"`
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessages, arg.ConversationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesRow{}
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Type,
			&i.Content,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
			&i.SenderAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserConversations = `-- name: ListUserConversations :many
SELECT DISTINCT c.id, c.type, c.name, c.event_id, c.created_at, c.updated_at FROM conversations c
JOIN conversation_members cm ON c.id = cm.conversation_id
WHERE cm.user_id = $1
ORDER BY c.updated_at DESC NULLS LAST
LIMIT $2 OFFSET $3
`

type ListUserConversationsParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListUserConversations(ctx context.Context, arg ListUserConversationsParams) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, listUserConversations, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.EventID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversationTimestamp = `-- name: UpdateConversationTimestamp :exec
UPDATE conversations SET updated_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateConversationTimestamp(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateConversationTimestamp, id)
	return err
}

const updateLastReadAt = `-- name: UpdateLastReadAt :exec
UPDATE conversation_members SET last_read_at = NOW()
WHERE conversation_id = $1 AND user_id = $2
`

type UpdateLastReadAtParams struct {
	ConversationID string `json:"conversation_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) UpdateLastReadAt(ctx context.Context, arg UpdateLastReadAtParams) error {
	_, err := q.db.ExecContext(ctx, updateLastReadAt, arg.ConversationID, arg.UserID)
	return err
}
