// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: explore.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const checkout = `-- name: Checkout :exec
UPDATE check_ins SET checked_out_at = NOW()
WHERE user_id = $1 AND checked_out_at IS NULL
`

func (q *Queries) Checkout(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, checkout, userID)
	return err
}

const countAllEvents = `-- name: CountAllEvents :one
SELECT COUNT(*) FROM events
`

func (q *Queries) CountAllEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCheckIns = `-- name: CountCheckIns :one
SELECT COUNT(*) FROM check_ins
`

func (q *Queries) CountCheckIns(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCheckIns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEventParticipants = `-- name: CountEventParticipants :one
SELECT COUNT(*) FROM event_participants WHERE event_id = $1
`

func (q *Queries) CountEventParticipants(ctx context.Context, eventID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEventParticipants, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLocations = `-- name: CountLocations :one
SELECT COUNT(*) FROM locations
WHERE ($1::uuid IS NULL OR category_id = $1)
`

func (q *Queries) CountLocations(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLocations, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUpcomingEvents = `-- name: CountUpcomingEvents :one
SELECT COUNT(*) FROM events WHERE start_time > NOW()
`

func (q *Queries) CountUpcomingEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUpcomingEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCheckIn = `-- name: CreateCheckIn :one
INSERT INTO check_ins (user_id, location_id)
VALUES ($1, $2)
RETURNING id, user_id, location_id, checked_in_at, checked_out_at
`

type CreateCheckInParams struct {
	UserID     string `json:"user_id"`
	LocationID string `json:"location_id"`
}

func (q *Queries) CreateCheckIn(ctx context.Context, arg CreateCheckInParams) (CheckIn, error) {
	row := q.db.QueryRowContext(ctx, createCheckIn, arg.UserID, arg.LocationID)
	var i CheckIn
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LocationID,
		&i.CheckedInAt,
		&i.CheckedOutAt,
	)
	return i, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (title, description, location_id, lat, lng, start_time, end_time, max_participants, filters, image_url, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, title, description, location_id, lat, lng, start_time, end_time, max_participants, filters, image_url, created_by, created_at, updated_at
`

type CreateEventParams struct {
	Title           string          `json:"title"`
	Description     sql.NullString  `json:"description"`
	LocationID      uuid.NullUUID   `json:"location_id"`
	Lat             float64         `json:"lat"`
	Lng             float64         `json:"lng"`
	StartTime       time.Time       `json:"start_time"`
	EndTime         time.Time       `json:"end_time"`
	MaxParticipants sql.NullInt32   `json:"max_participants"`
	Filters         json.RawMessage `json:"filters"`
	ImageUrl        sql.NullString  `json:"image_url"`
	CreatedBy       string          `json:"created_by"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.Title,
		arg.Description,
		arg.LocationID,
		arg.Lat,
		arg.Lng,
		arg.StartTime,
		arg.EndTime,
		arg.MaxParticipants,
		arg.Filters,
		arg.ImageUrl,
		arg.CreatedBy,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.LocationID,
		&i.Lat,
		&i.Lng,
		&i.StartTime,
		&i.EndTime,
		&i.MaxParticipants,
		&i.Filters,
		&i.ImageUrl,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (name, description, category_id, lat, lng, address, image_url, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, description, category_id, lat, lng, address, image_url, created_by, created_at, updated_at
`

type CreateLocationParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CategoryID  string         `json:"category_id"`
	Lat         float64        `json:"lat"`
	Lng         float64        `json:"lng"`
	Address     sql.NullString `json:"address"`
	ImageUrl    sql.NullString `json:"image_url"`
	CreatedBy   uuid.NullUUID  `json:"created_by"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRowContext(ctx, createLocation,
		arg.Name,
		arg.Description,
		arg.CategoryID,
		arg.Lat,
		arg.Lng,
		arg.Address,
		arg.ImageUrl,
		arg.CreatedBy,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.Lat,
		&i.Lng,
		&i.Address,
		&i.ImageUrl,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLocationCategory = `-- name: CreateLocationCategory :one
INSERT INTO location_categories (name) VALUES ($1) RETURNING id, name, created_at
`

func (q *Queries) CreateLocationCategory(ctx context.Context, name string) (LocationCategory, error) {
	row := q.db.QueryRowContext(ctx, createLocationCategory, name)
	var i LocationCategory
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, id)
	return err
}

const deleteLocation = `-- name: DeleteLocation :exec
DELETE FROM locations WHERE id = $1
`

func (q *Queries) DeleteLocation(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteLocation, id)
	return err
}

const deleteLocationCategory = `-- name: DeleteLocationCategory :exec
DELETE FROM location_categories WHERE id = $1
`

func (q *Queries) DeleteLocationCategory(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteLocationCategory, id)
	return err
}

const getActiveCheckIn = `-- name: GetActiveCheckIn :one
SELECT id, user_id, location_id, checked_in_at, checked_out_at FROM check_ins
WHERE user_id = $1 AND checked_out_at IS NULL
LIMIT 1
`

func (q *Queries) GetActiveCheckIn(ctx context.Context, userID string) (CheckIn, error) {
	row := q.db.QueryRowContext(ctx, getActiveCheckIn, userID)
	var i CheckIn
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LocationID,
		&i.CheckedInAt,
		&i.CheckedOutAt,
	)
	return i, err
}

const getActiveCheckInsByLocation = `-- name: GetActiveCheckInsByLocation :many
SELECT c.id, c.user_id, c.location_id, c.checked_in_at, c.checked_out_at, u.first_name, u.last_name, u.avatar_url as user_avatar
FROM check_ins c
JOIN users u ON c.user_id = u.id
WHERE c.location_id = $1 AND c.checked_out_at IS NULL
`

type GetActiveCheckInsByLocationRow struct {
	ID           string         `json:"id"`
	UserID       string         `json:"user_id"`
	LocationID   string         `json:"location_id"`
	CheckedInAt  time.Time      `json:"checked_in_at"`
	CheckedOutAt sql.NullTime   `json:"checked_out_at"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	UserAvatar   sql.NullString `json:"user_avatar"`
}

func (q *Queries) GetActiveCheckInsByLocation(ctx context.Context, locationID string) ([]GetActiveCheckInsByLocationRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveCheckInsByLocation, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveCheckInsByLocationRow{}
	for rows.Next() {
		var i GetActiveCheckInsByLocationRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LocationID,
			&i.CheckedInAt,
			&i.CheckedOutAt,
			&i.FirstName,
			&i.LastName,
			&i.UserAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, title, description, location_id, lat, lng, start_time, end_time, max_participants, filters, image_url, created_by, created_at, updated_at FROM events WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id string) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.LocationID,
		&i.Lat,
		&i.Lng,
		&i.StartTime,
		&i.EndTime,
		&i.MaxParticipants,
		&i.Filters,
		&i.ImageUrl,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventParticipants = `-- name: GetEventParticipants :many
SELECT ep.event_id, ep.user_id, ep.status, ep.joined_at, u.first_name, u.last_name, u.avatar_url as user_avatar
FROM event_participants ep
JOIN users u ON ep.user_id = u.id
WHERE ep.event_id = $1
`

type GetEventParticipantsRow struct {
	EventID    string         `json:"event_id"`
	UserID     string         `json:"user_id"`
	Status     string         `json:"status"`
	JoinedAt   time.Time      `json:"joined_at"`
	FirstName  string         `json:"first_name"`
	LastName   string         `json:"last_name"`
	UserAvatar sql.NullString `json:"user_avatar"`
}

func (q *Queries) GetEventParticipants(ctx context.Context, eventID string) ([]GetEventParticipantsRow, error) {
	rows, err := q.db.QueryContext(ctx, getEventParticipants, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEventParticipantsRow{}
	for rows.Next() {
		var i GetEventParticipantsRow
		if err := rows.Scan(
			&i.EventID,
			&i.UserID,
			&i.Status,
			&i.JoinedAt,
			&i.FirstName,
			&i.LastName,
			&i.UserAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLocationByID = `-- name: GetLocationByID :one
SELECT id, name, description, category_id, lat, lng, address, image_url, created_by, created_at, updated_at FROM locations WHERE id = $1
`

func (q *Queries) GetLocationByID(ctx context.Context, id string) (Location, error) {
	row := q.db.QueryRowContext(ctx, getLocationByID, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.Lat,
		&i.Lng,
		&i.Address,
		&i.ImageUrl,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocationCategories = `-- name: GetLocationCategories :many
SELECT id, name, created_at FROM location_categories ORDER BY name
`

func (q *Queries) GetLocationCategories(ctx context.Context) ([]LocationCategory, error) {
	rows, err := q.db.QueryContext(ctx, getLocationCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LocationCategory{}
	for rows.Next() {
		var i LocationCategory
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNearbyLocations = `-- name: GetNearbyLocations :many
SELECT l.id, l.name, l.description, l.category_id, l.lat, l.lng, l.address, l.image_url, l.created_by, l.created_at, l.updated_at, lc.name as category_name,
  earth_distance(
    ll_to_earth(l.lat, l.lng),
    ll_to_earth($1, $2)
  ) as distance_meters
FROM locations l
JOIN location_categories lc ON l.category_id = lc.id
WHERE earth_distance(
    ll_to_earth(l.lat, l.lng),
    ll_to_earth($1, $2)
  ) <= $3
ORDER BY distance_meters
`

type GetNearbyLocationsParams struct {
	LlToEarth   float64 `json:"ll_to_earth"`
	LlToEarth_2 float64 `json:"ll_to_earth_2"`
	Lat         float64 `json:"lat"`
}

type GetNearbyLocationsRow struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	CategoryID     string         `json:"category_id"`
	Lat            float64        `json:"lat"`
	Lng            float64        `json:"lng"`
	Address        sql.NullString `json:"address"`
	ImageUrl       sql.NullString `json:"image_url"`
	CreatedBy      uuid.NullUUID  `json:"created_by"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	CategoryName   string         `json:"category_name"`
	DistanceMeters float64        `json:"distance_meters"`
}

func (q *Queries) GetNearbyLocations(ctx context.Context, arg GetNearbyLocationsParams) ([]GetNearbyLocationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getNearbyLocations, arg.LlToEarth, arg.LlToEarth_2, arg.Lat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNearbyLocationsRow{}
	for rows.Next() {
		var i GetNearbyLocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CategoryID,
			&i.Lat,
			&i.Lng,
			&i.Address,
			&i.ImageUrl,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.DistanceMeters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isEventParticipant = `-- name: IsEventParticipant :one
SELECT EXISTS(SELECT 1 FROM event_participants WHERE event_id = $1 AND user_id = $2)
`

type IsEventParticipantParams struct {
	EventID string `json:"event_id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) IsEventParticipant(ctx context.Context, arg IsEventParticipantParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isEventParticipant, arg.EventID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const joinEvent = `-- name: JoinEvent :one
INSERT INTO event_participants (event_id, user_id, status)
VALUES ($1, $2, $3)
ON CONFLICT (event_id, user_id) DO UPDATE SET status = $3
RETURNING event_id, user_id, status, joined_at
`

type JoinEventParams struct {
	EventID string `json:"event_id"`
	UserID  string `json:"user_id"`
	Status  string `json:"status"`
}

func (q *Queries) JoinEvent(ctx context.Context, arg JoinEventParams) (EventParticipant, error) {
	row := q.db.QueryRowContext(ctx, joinEvent, arg.EventID, arg.UserID, arg.Status)
	var i EventParticipant
	err := row.Scan(
		&i.EventID,
		&i.UserID,
		&i.Status,
		&i.JoinedAt,
	)
	return i, err
}

const leaveEvent = `-- name: LeaveEvent :exec
DELETE FROM event_participants WHERE event_id = $1 AND user_id = $2
`

type LeaveEventParams struct {
	EventID string `json:"event_id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) LeaveEvent(ctx context.Context, arg LeaveEventParams) error {
	_, err := q.db.ExecContext(ctx, leaveEvent, arg.EventID, arg.UserID)
	return err
}

const listAllEventsAdmin = `-- name: ListAllEventsAdmin :many
SELECT id, title, description, location_id, lat, lng, start_time, end_time, max_participants, filters, image_url, created_by, created_at, updated_at FROM events ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListAllEventsAdminParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllEventsAdmin(ctx context.Context, arg ListAllEventsAdminParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listAllEventsAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.LocationID,
			&i.Lat,
			&i.Lng,
			&i.StartTime,
			&i.EndTime,
			&i.MaxParticipants,
			&i.Filters,
			&i.ImageUrl,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, title, description, location_id, lat, lng, start_time, end_time, max_participants, filters, image_url, created_by, created_at, updated_at FROM events
WHERE start_time > NOW()
ORDER BY start_time ASC
LIMIT $1 OFFSET $2
`

type ListEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.LocationID,
			&i.Lat,
			&i.Lng,
			&i.StartTime,
			&i.EndTime,
			&i.MaxParticipants,
			&i.Filters,
			&i.ImageUrl,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocations = `-- name: ListLocations :many
SELECT l.id, l.name, l.description, l.category_id, l.lat, l.lng, l.address, l.image_url, l.created_by, l.created_at, l.updated_at, lc.name as category_name FROM locations l
JOIN location_categories lc ON l.category_id = lc.id
WHERE ($1::uuid IS NULL OR l.category_id = $1)
ORDER BY l.name
LIMIT $2 OFFSET $3
`

type ListLocationsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListLocationsRow struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	CategoryID   string         `json:"category_id"`
	Lat          float64        `json:"lat"`
	Lng          float64        `json:"lng"`
	Address      sql.NullString `json:"address"`
	ImageUrl     sql.NullString `json:"image_url"`
	CreatedBy    uuid.NullUUID  `json:"created_by"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	CategoryName string         `json:"category_name"`
}

func (q *Queries) ListLocations(ctx context.Context, arg ListLocationsParams) ([]ListLocationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLocations, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLocationsRow{}
	for rows.Next() {
		var i ListLocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CategoryID,
			&i.Lat,
			&i.Lng,
			&i.Address,
			&i.ImageUrl,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET
  title = COALESCE($2, title),
  description = COALESCE($3, description),
  lat = COALESCE($4, lat),
  lng = COALESCE($5, lng),
  start_time = COALESCE($6, start_time),
  end_time = COALESCE($7, end_time),
  max_participants = COALESCE($8, max_participants),
  filters = COALESCE($9, filters),
  image_url = COALESCE($10, image_url)
WHERE id = $1
RETURNING id, title, description, location_id, lat, lng, start_time, end_time, max_participants, filters, image_url, created_by, created_at, updated_at
`

type UpdateEventParams struct {
	ID              string                `json:"id"`
	Title           sql.NullString        `json:"title"`
	Description     sql.NullString        `json:"description"`
	Lat             sql.NullFloat64       `json:"lat"`
	Lng             sql.NullFloat64       `json:"lng"`
	StartTime       sql.NullTime          `json:"start_time"`
	EndTime         sql.NullTime          `json:"end_time"`
	MaxParticipants sql.NullInt32         `json:"max_participants"`
	Filters         pqtype.NullRawMessage `json:"filters"`
	ImageUrl        sql.NullString        `json:"image_url"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, updateEvent,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Lat,
		arg.Lng,
		arg.StartTime,
		arg.EndTime,
		arg.MaxParticipants,
		arg.Filters,
		arg.ImageUrl,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.LocationID,
		&i.Lat,
		&i.Lng,
		&i.StartTime,
		&i.EndTime,
		&i.MaxParticipants,
		&i.Filters,
		&i.ImageUrl,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE locations
SET
  name = COALESCE($2, name),
  description = COALESCE($3, description),
  category_id = COALESCE($4, category_id),
  lat = COALESCE($5, lat),
  lng = COALESCE($6, lng),
  address = COALESCE($7, address),
  image_url = COALESCE($8, image_url)
WHERE id = $1
RETURNING id, name, description, category_id, lat, lng, address, image_url, created_by, created_at, updated_at
`

type UpdateLocationParams struct {
	ID          string          `json:"id"`
	Name        sql.NullString  `json:"name"`
	Description sql.NullString  `json:"description"`
	CategoryID  uuid.NullUUID   `json:"category_id"`
	Lat         sql.NullFloat64 `json:"lat"`
	Lng         sql.NullFloat64 `json:"lng"`
	Address     sql.NullString  `json:"address"`
	ImageUrl    sql.NullString  `json:"image_url"`
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error) {
	row := q.db.QueryRowContext(ctx, updateLocation,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CategoryID,
		arg.Lat,
		arg.Lng,
		arg.Address,
		arg.ImageUrl,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.Lat,
		&i.Lng,
		&i.Address,
		&i.ImageUrl,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
