// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: matches.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const checkForMatch = `-- name: CheckForMatch :one
SELECT EXISTS(
  SELECT 1 FROM swipes s1
  JOIN swipes s2 ON s1.swiper_pet_id = s2.swiped_pet_id AND s1.swiped_pet_id = s2.swiper_pet_id
  WHERE s1.swiper_pet_id = $1 AND s2.direction = 'like'
)
`

func (q *Queries) CheckForMatch(ctx context.Context, swiperPetID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkForMatch, swiperPetID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countMatches = `-- name: CountMatches :one
SELECT COUNT(*) FROM matches
`

func (q *Queries) CountMatches(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMatches)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMatchesByUserID = `-- name: CountMatchesByUserID :one
SELECT COUNT(*) FROM matches m
JOIN pets p1 ON m.pet_id_1 = p1.id
JOIN pets p2 ON m.pet_id_2 = p2.id
WHERE p1.user_id = $1 OR p2.user_id = $1
`

func (q *Queries) CountMatchesByUserID(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMatchesByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserMatches = `-- name: CountUserMatches :one
SELECT COUNT(*) FROM matches m
JOIN pets p ON (p.id = m.pet_id_1 OR p.id = m.pet_id_2)
WHERE p.user_id = $1
`

func (q *Queries) CountUserMatches(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserMatches, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (pet_id_1, pet_id_2)
VALUES (
  LEAST($1, $2),
  GREATEST($1, $2)
)
ON CONFLICT (pet_id_1, pet_id_2) DO NOTHING
RETURNING id, pet_id_1, pet_id_2, matched_at
`

type CreateMatchParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRowContext(ctx, createMatch, arg.Column1, arg.Column2)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.PetID1,
		&i.PetID2,
		&i.MatchedAt,
	)
	return i, err
}

const createSwipe = `-- name: CreateSwipe :one
INSERT INTO swipes (swiper_pet_id, swiped_pet_id, direction)
VALUES ($1, $2, $3)
ON CONFLICT (swiper_pet_id, swiped_pet_id) DO NOTHING
RETURNING id, swiper_pet_id, swiped_pet_id, direction, created_at
`

type CreateSwipeParams struct {
	SwiperPetID string `json:"swiper_pet_id"`
	SwipedPetID string `json:"swiped_pet_id"`
	Direction   string `json:"direction"`
}

func (q *Queries) CreateSwipe(ctx context.Context, arg CreateSwipeParams) (Swipe, error) {
	row := q.db.QueryRowContext(ctx, createSwipe, arg.SwiperPetID, arg.SwipedPetID, arg.Direction)
	var i Swipe
	err := row.Scan(
		&i.ID,
		&i.SwiperPetID,
		&i.SwipedPetID,
		&i.Direction,
		&i.CreatedAt,
	)
	return i, err
}

const getPetSwipeStats = `-- name: GetPetSwipeStats :one
SELECT
  COUNT(*) FILTER (WHERE direction = 'like') as total_likes,
  COUNT(*) FILTER (WHERE direction = 'pass') as total_passes
FROM swipes WHERE swiper_pet_id = $1
`

type GetPetSwipeStatsRow struct {
	TotalLikes  int64 `json:"total_likes"`
	TotalPasses int64 `json:"total_passes"`
}

func (q *Queries) GetPetSwipeStats(ctx context.Context, swiperPetID string) (GetPetSwipeStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getPetSwipeStats, swiperPetID)
	var i GetPetSwipeStatsRow
	err := row.Scan(&i.TotalLikes, &i.TotalPasses)
	return i, err
}

const hasLikedBack = `-- name: HasLikedBack :one
SELECT EXISTS(SELECT 1 FROM swipes WHERE swiper_pet_id = $1 AND swiped_pet_id = $2 AND direction = 'like')
`

type HasLikedBackParams struct {
	SwiperPetID string `json:"swiper_pet_id"`
	SwipedPetID string `json:"swiped_pet_id"`
}

func (q *Queries) HasLikedBack(ctx context.Context, arg HasLikedBackParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasLikedBack, arg.SwiperPetID, arg.SwipedPetID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasSwiped = `-- name: HasSwiped :one
SELECT EXISTS(SELECT 1 FROM swipes WHERE swiper_pet_id = $1 AND swiped_pet_id = $2)
`

type HasSwipedParams struct {
	SwiperPetID string `json:"swiper_pet_id"`
	SwipedPetID string `json:"swiped_pet_id"`
}

func (q *Queries) HasSwiped(ctx context.Context, arg HasSwipedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasSwiped, arg.SwiperPetID, arg.SwipedPetID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listMatchesByPetIDs = `-- name: ListMatchesByPetIDs :many
SELECT m.id, m.pet_id_1, m.pet_id_2, m.matched_at, p1.name as pet1_name, p1.avatar_url as pet1_avatar,
       p2.name as pet2_name, p2.avatar_url as pet2_avatar
FROM matches m
JOIN pets p1 ON m.pet_id_1 = p1.id
JOIN pets p2 ON m.pet_id_2 = p2.id
WHERE m.pet_id_1 = ANY($1::uuid[]) OR m.pet_id_2 = ANY($1::uuid[])
`

type ListMatchesByPetIDsRow struct {
	ID         string         `json:"id"`
	PetID1     string         `json:"pet_id_1"`
	PetID2     string         `json:"pet_id_2"`
	MatchedAt  time.Time      `json:"matched_at"`
	Pet1Name   string         `json:"pet1_name"`
	Pet1Avatar sql.NullString `json:"pet1_avatar"`
	Pet2Name   string         `json:"pet2_name"`
	Pet2Avatar sql.NullString `json:"pet2_avatar"`
}

func (q *Queries) ListMatchesByPetIDs(ctx context.Context, dollar_1 []string) ([]ListMatchesByPetIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMatchesByPetIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMatchesByPetIDsRow{}
	for rows.Next() {
		var i ListMatchesByPetIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.PetID1,
			&i.PetID2,
			&i.MatchedAt,
			&i.Pet1Name,
			&i.Pet1Avatar,
			&i.Pet2Name,
			&i.Pet2Avatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesByUserID = `-- name: ListMatchesByUserID :many
SELECT m.id, m.pet_id_1, m.pet_id_2, m.matched_at, p1.name as pet1_name, p1.avatar_url as pet1_avatar,
       p2.name as pet2_name, p2.avatar_url as pet2_avatar,
       u1.first_name || ' ' || u1.last_name as pet1_owner_name,
       u2.first_name || ' ' || u2.last_name as pet2_owner_name
FROM matches m
JOIN pets p1 ON m.pet_id_1 = p1.id
JOIN pets p2 ON m.pet_id_2 = p2.id
JOIN users u1 ON p1.user_id = u1.id
JOIN users u2 ON p2.user_id = u2.id
WHERE p1.user_id = $1 OR p2.user_id = $1
ORDER BY m.matched_at DESC
LIMIT $2 OFFSET $3
`

type ListMatchesByUserIDParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListMatchesByUserIDRow struct {
	ID            string         `json:"id"`
	PetID1        string         `json:"pet_id_1"`
	PetID2        string         `json:"pet_id_2"`
	MatchedAt     time.Time      `json:"matched_at"`
	Pet1Name      string         `json:"pet1_name"`
	Pet1Avatar    sql.NullString `json:"pet1_avatar"`
	Pet2Name      string         `json:"pet2_name"`
	Pet2Avatar    sql.NullString `json:"pet2_avatar"`
	Pet1OwnerName interface{}    `json:"pet1_owner_name"`
	Pet2OwnerName interface{}    `json:"pet2_owner_name"`
}

func (q *Queries) ListMatchesByUserID(ctx context.Context, arg ListMatchesByUserIDParams) ([]ListMatchesByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listMatchesByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMatchesByUserIDRow{}
	for rows.Next() {
		var i ListMatchesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PetID1,
			&i.PetID2,
			&i.MatchedAt,
			&i.Pet1Name,
			&i.Pet1Avatar,
			&i.Pet2Name,
			&i.Pet2Avatar,
			&i.Pet1OwnerName,
			&i.Pet2OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
