// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type CheckIn struct {
	ID           string       `json:"id"`
	UserID       string       `json:"user_id"`
	LocationID   string       `json:"location_id"`
	CheckedInAt  time.Time    `json:"checked_in_at"`
	CheckedOutAt sql.NullTime `json:"checked_out_at"`
}

type Conversation struct {
	ID        string         `json:"id"`
	Type      string         `json:"type"`
	Name      sql.NullString `json:"name"`
	EventID   uuid.NullUUID  `json:"event_id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type ConversationMember struct {
	ConversationID string        `json:"conversation_id"`
	UserID         string        `json:"user_id"`
	PetID          uuid.NullUUID `json:"pet_id"`
	JoinedAt       time.Time     `json:"joined_at"`
	LastReadAt     sql.NullTime  `json:"last_read_at"`
}

type Event struct {
	ID              string          `json:"id"`
	Title           string          `json:"title"`
	Description     sql.NullString  `json:"description"`
	LocationID      uuid.NullUUID   `json:"location_id"`
	Lat             float64         `json:"lat"`
	Lng             float64         `json:"lng"`
	StartTime       time.Time       `json:"start_time"`
	EndTime         time.Time       `json:"end_time"`
	MaxParticipants sql.NullInt32   `json:"max_participants"`
	Filters         json.RawMessage `json:"filters"`
	ImageUrl        sql.NullString  `json:"image_url"`
	CreatedBy       string          `json:"created_by"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

type EventParticipant struct {
	EventID  string    `json:"event_id"`
	UserID   string    `json:"user_id"`
	Status   string    `json:"status"`
	JoinedAt time.Time `json:"joined_at"`
}

type Location struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CategoryID  string         `json:"category_id"`
	Lat         float64        `json:"lat"`
	Lng         float64        `json:"lng"`
	Address     sql.NullString `json:"address"`
	ImageUrl    sql.NullString `json:"image_url"`
	CreatedBy   uuid.NullUUID  `json:"created_by"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type LocationCategory struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Match struct {
	ID        string    `json:"id"`
	PetID1    string    `json:"pet_id_1"`
	PetID2    string    `json:"pet_id_2"`
	MatchedAt time.Time `json:"matched_at"`
}

type Message struct {
	ID             string    `json:"id"`
	ConversationID string    `json:"conversation_id"`
	SenderID       string    `json:"sender_id"`
	Type           string    `json:"type"`
	Content        string    `json:"content"`
	CreatedAt      time.Time `json:"created_at"`
}

type Pet struct {
	ID            string         `json:"id"`
	UserID        string         `json:"user_id"`
	Name          string         `json:"name"`
	SpeciesID     string         `json:"species_id"`
	BreedID       uuid.NullUUID  `json:"breed_id"`
	Age           sql.NullInt32  `json:"age"`
	ActivityLevel int16          `json:"activity_level"`
	Neutered      bool           `json:"neutered"`
	AvatarUrl     sql.NullString `json:"avatar_url"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type PetBreed struct {
	ID        string    `json:"id"`
	SpeciesID string    `json:"species_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type PetCompatibility struct {
	PetID           string `json:"pet_id"`
	CompatibilityID string `json:"compatibility_id"`
}

type PetCompatibilityOption struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type PetHobby struct {
	PetID   string `json:"pet_id"`
	HobbyID string `json:"hobby_id"`
}

type PetHobbyOption struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type PetSpecy struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Post struct {
	ID            string      `json:"id"`
	UserID        string      `json:"user_id"`
	Content       string      `json:"content"`
	ImageUrls     []string    `json:"image_urls"`
	LikeCount     int32       `json:"like_count"`
	CongratsCount int32       `json:"congrats_count"`
	FunnyCount    int32       `json:"funny_count"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	SearchVector  interface{} `json:"search_vector"`
}

type PostReaction struct {
	ID        string    `json:"id"`
	PostID    string    `json:"post_id"`
	UserID    string    `json:"user_id"`
	Type      string    `json:"type"`
	CreatedAt time.Time `json:"created_at"`
}

type RefreshToken struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Swipe struct {
	ID          string    `json:"id"`
	SwiperPetID string    `json:"swiper_pet_id"`
	SwipedPetID string    `json:"swiped_pet_id"`
	Direction   string    `json:"direction"`
	CreatedAt   time.Time `json:"created_at"`
}

type User struct {
	ID           string         `json:"id"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Phone        sql.NullString `json:"phone"`
	Gender       sql.NullString `json:"gender"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	Role         string         `json:"role"`
	IsBanned     bool           `json:"is_banned"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}
