// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: options.sql

package sqlcgen

import (
	"context"
	"time"
)

const createBreed = `-- name: CreateBreed :one
INSERT INTO pet_breeds (species_id, name) VALUES ($1, $2) RETURNING id, species_id, name, created_at
`

type CreateBreedParams struct {
	SpeciesID string `json:"species_id"`
	Name      string `json:"name"`
}

func (q *Queries) CreateBreed(ctx context.Context, arg CreateBreedParams) (PetBreed, error) {
	row := q.db.QueryRowContext(ctx, createBreed, arg.SpeciesID, arg.Name)
	var i PetBreed
	err := row.Scan(
		&i.ID,
		&i.SpeciesID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createCompatibilityOption = `-- name: CreateCompatibilityOption :one
INSERT INTO pet_compatibility_options (name) VALUES ($1) RETURNING id, name, created_at
`

func (q *Queries) CreateCompatibilityOption(ctx context.Context, name string) (PetCompatibilityOption, error) {
	row := q.db.QueryRowContext(ctx, createCompatibilityOption, name)
	var i PetCompatibilityOption
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createHobbyOption = `-- name: CreateHobbyOption :one
INSERT INTO pet_hobby_options (name) VALUES ($1) RETURNING id, name, created_at
`

func (q *Queries) CreateHobbyOption(ctx context.Context, name string) (PetHobbyOption, error) {
	row := q.db.QueryRowContext(ctx, createHobbyOption, name)
	var i PetHobbyOption
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createSpecies = `-- name: CreateSpecies :one
INSERT INTO pet_species (name) VALUES ($1) RETURNING id, name, created_at
`

func (q *Queries) CreateSpecies(ctx context.Context, name string) (PetSpecy, error) {
	row := q.db.QueryRowContext(ctx, createSpecies, name)
	var i PetSpecy
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteBreed = `-- name: DeleteBreed :exec
DELETE FROM pet_breeds WHERE id = $1
`

func (q *Queries) DeleteBreed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteBreed, id)
	return err
}

const deleteCompatibilityOption = `-- name: DeleteCompatibilityOption :exec
DELETE FROM pet_compatibility_options WHERE id = $1
`

func (q *Queries) DeleteCompatibilityOption(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCompatibilityOption, id)
	return err
}

const deleteHobbyOption = `-- name: DeleteHobbyOption :exec
DELETE FROM pet_hobby_options WHERE id = $1
`

func (q *Queries) DeleteHobbyOption(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteHobbyOption, id)
	return err
}

const deleteSpecies = `-- name: DeleteSpecies :exec
DELETE FROM pet_species WHERE id = $1
`

func (q *Queries) DeleteSpecies(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSpecies, id)
	return err
}

const getAllBreeds = `-- name: GetAllBreeds :many
SELECT b.id, b.species_id, b.name, b.created_at, s.name as species_name FROM pet_breeds b
JOIN pet_species s ON b.species_id = s.id
ORDER BY s.name, b.name
`

type GetAllBreedsRow struct {
	ID          string    `json:"id"`
	SpeciesID   string    `json:"species_id"`
	Name        string    `json:"name"`
	CreatedAt   time.Time `json:"created_at"`
	SpeciesName string    `json:"species_name"`
}

func (q *Queries) GetAllBreeds(ctx context.Context) ([]GetAllBreedsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllBreeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllBreedsRow{}
	for rows.Next() {
		var i GetAllBreedsRow
		if err := rows.Scan(
			&i.ID,
			&i.SpeciesID,
			&i.Name,
			&i.CreatedAt,
			&i.SpeciesName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBreedsBySpecies = `-- name: GetBreedsBySpecies :many
SELECT id, species_id, name, created_at FROM pet_breeds WHERE species_id = $1 ORDER BY name
`

func (q *Queries) GetBreedsBySpecies(ctx context.Context, speciesID string) ([]PetBreed, error) {
	rows, err := q.db.QueryContext(ctx, getBreedsBySpecies, speciesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PetBreed{}
	for rows.Next() {
		var i PetBreed
		if err := rows.Scan(
			&i.ID,
			&i.SpeciesID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompatibilityOptions = `-- name: GetCompatibilityOptions :many
SELECT id, name, created_at FROM pet_compatibility_options ORDER BY name
`

func (q *Queries) GetCompatibilityOptions(ctx context.Context) ([]PetCompatibilityOption, error) {
	rows, err := q.db.QueryContext(ctx, getCompatibilityOptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PetCompatibilityOption{}
	for rows.Next() {
		var i PetCompatibilityOption
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHobbyOptions = `-- name: GetHobbyOptions :many
SELECT id, name, created_at FROM pet_hobby_options ORDER BY name
`

func (q *Queries) GetHobbyOptions(ctx context.Context) ([]PetHobbyOption, error) {
	rows, err := q.db.QueryContext(ctx, getHobbyOptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PetHobbyOption{}
	for rows.Next() {
		var i PetHobbyOption
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpecies = `-- name: GetSpecies :many
SELECT id, name, created_at FROM pet_species ORDER BY name
`

func (q *Queries) GetSpecies(ctx context.Context) ([]PetSpecy, error) {
	rows, err := q.db.QueryContext(ctx, getSpecies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PetSpecy{}
	for rows.Next() {
		var i PetSpecy
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
