// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pets.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countAllPets = `-- name: CountAllPets :one
SELECT COUNT(*) FROM pets
WHERE ($1::text IS NULL OR pets.name ILIKE '%' || $1 || '%')
`

func (q *Queries) CountAllPets(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllPets, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPets = `-- name: CountPets :one
SELECT COUNT(*) FROM pets
`

func (q *Queries) CountPets(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPets)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPet = `-- name: CreatePet :one
INSERT INTO pets (user_id, name, species_id, breed_id, age, activity_level, neutered, avatar_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, name, species_id, breed_id, age, activity_level, neutered, avatar_url, created_at, updated_at
`

type CreatePetParams struct {
	UserID        string         `json:"user_id"`
	Name          string         `json:"name"`
	SpeciesID     string         `json:"species_id"`
	BreedID       uuid.NullUUID  `json:"breed_id"`
	Age           sql.NullInt32  `json:"age"`
	ActivityLevel int16          `json:"activity_level"`
	Neutered      bool           `json:"neutered"`
	AvatarUrl     sql.NullString `json:"avatar_url"`
}

func (q *Queries) CreatePet(ctx context.Context, arg CreatePetParams) (Pet, error) {
	row := q.db.QueryRowContext(ctx, createPet,
		arg.UserID,
		arg.Name,
		arg.SpeciesID,
		arg.BreedID,
		arg.Age,
		arg.ActivityLevel,
		arg.Neutered,
		arg.AvatarUrl,
	)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.SpeciesID,
		&i.BreedID,
		&i.Age,
		&i.ActivityLevel,
		&i.Neutered,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePet = `-- name: DeletePet :exec
DELETE FROM pets WHERE id = $1 AND user_id = $2
`

type DeletePetParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeletePet(ctx context.Context, arg DeletePetParams) error {
	_, err := q.db.ExecContext(ctx, deletePet, arg.ID, arg.UserID)
	return err
}

const getPetByID = `-- name: GetPetByID :one
SELECT id, user_id, name, species_id, breed_id, age, activity_level, neutered, avatar_url, created_at, updated_at FROM pets WHERE id = $1
`

func (q *Queries) GetPetByID(ctx context.Context, id string) (Pet, error) {
	row := q.db.QueryRowContext(ctx, getPetByID, id)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.SpeciesID,
		&i.BreedID,
		&i.Age,
		&i.ActivityLevel,
		&i.Neutered,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPetCompatibilities = `-- name: GetPetCompatibilities :many
SELECT pet_compatibility_options.id, pet_compatibility_options.name, pet_compatibility_options.created_at FROM pet_compatibilities
JOIN pet_compatibility_options ON pet_compatibilities.compatibility_id = pet_compatibility_options.id
WHERE pet_compatibilities.pet_id = $1
`

func (q *Queries) GetPetCompatibilities(ctx context.Context, petID string) ([]PetCompatibilityOption, error) {
	rows, err := q.db.QueryContext(ctx, getPetCompatibilities, petID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PetCompatibilityOption{}
	for rows.Next() {
		var i PetCompatibilityOption
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPetHobbies = `-- name: GetPetHobbies :many
SELECT pet_hobby_options.id, pet_hobby_options.name, pet_hobby_options.created_at FROM pet_hobbies
JOIN pet_hobby_options ON pet_hobbies.hobby_id = pet_hobby_options.id
WHERE pet_hobbies.pet_id = $1
`

func (q *Queries) GetPetHobbies(ctx context.Context, petID string) ([]PetHobbyOption, error) {
	rows, err := q.db.QueryContext(ctx, getPetHobbies, petID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PetHobbyOption{}
	for rows.Next() {
		var i PetHobbyOption
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPetCompatibility = `-- name: InsertPetCompatibility :exec
INSERT INTO pet_compatibilities (pet_id, compatibility_id) VALUES ($1, $2)
`

type InsertPetCompatibilityParams struct {
	PetID           string `json:"pet_id"`
	CompatibilityID string `json:"compatibility_id"`
}

func (q *Queries) InsertPetCompatibility(ctx context.Context, arg InsertPetCompatibilityParams) error {
	_, err := q.db.ExecContext(ctx, insertPetCompatibility, arg.PetID, arg.CompatibilityID)
	return err
}

const insertPetHobby = `-- name: InsertPetHobby :exec
INSERT INTO pet_hobbies (pet_id, hobby_id) VALUES ($1, $2)
`

type InsertPetHobbyParams struct {
	PetID   string `json:"pet_id"`
	HobbyID string `json:"hobby_id"`
}

func (q *Queries) InsertPetHobby(ctx context.Context, arg InsertPetHobbyParams) error {
	_, err := q.db.ExecContext(ctx, insertPetHobby, arg.PetID, arg.HobbyID)
	return err
}

const listAllPets = `-- name: ListAllPets :many
SELECT pets.id, pets.user_id, pets.name, pets.species_id, pets.breed_id, pets.age, pets.activity_level, pets.neutered, pets.avatar_url, pets.created_at, pets.updated_at FROM pets
JOIN users ON pets.user_id = users.id
WHERE ($1::text IS NULL OR pets.name ILIKE '%' || $1 || '%')
ORDER BY pets.created_at DESC
LIMIT $2 OFFSET $3
`

type ListAllPetsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListAllPets(ctx context.Context, arg ListAllPetsParams) ([]Pet, error) {
	rows, err := q.db.QueryContext(ctx, listAllPets, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pet{}
	for rows.Next() {
		var i Pet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.SpeciesID,
			&i.BreedID,
			&i.Age,
			&i.ActivityLevel,
			&i.Neutered,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPetsByUserID = `-- name: ListPetsByUserID :many
SELECT id, user_id, name, species_id, breed_id, age, activity_level, neutered, avatar_url, created_at, updated_at FROM pets WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPetsByUserID(ctx context.Context, userID string) ([]Pet, error) {
	rows, err := q.db.QueryContext(ctx, listPetsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pet{}
	for rows.Next() {
		var i Pet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.SpeciesID,
			&i.BreedID,
			&i.Age,
			&i.ActivityLevel,
			&i.Neutered,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPetsForMatching = `-- name: ListPetsForMatching :many
SELECT DISTINCT p.id, p.user_id, p.name, p.species_id, p.breed_id, p.age, p.activity_level, p.neutered, p.avatar_url, p.created_at, p.updated_at FROM pets p
WHERE p.user_id != $1
  AND p.id NOT IN (
    SELECT swiped_pet_id FROM swipes WHERE swiper_pet_id = ANY($2::uuid[])
  )
  AND p.id NOT IN (
    SELECT CASE
      WHEN pet_id_1 = ANY($2::uuid[]) THEN pet_id_2
      ELSE pet_id_1
    END FROM matches
    WHERE pet_id_1 = ANY($2::uuid[]) OR pet_id_2 = ANY($2::uuid[])
  )
ORDER BY p.created_at DESC
LIMIT $3 OFFSET $4
`

type ListPetsForMatchingParams struct {
	UserID  string   `json:"user_id"`
	Column2 []string `json:"column_2"`
	Limit   int32    `json:"limit"`
	Offset  int32    `json:"offset"`
}

func (q *Queries) ListPetsForMatching(ctx context.Context, arg ListPetsForMatchingParams) ([]Pet, error) {
	rows, err := q.db.QueryContext(ctx, listPetsForMatching,
		arg.UserID,
		pq.Array(arg.Column2),
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pet{}
	for rows.Next() {
		var i Pet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.SpeciesID,
			&i.BreedID,
			&i.Age,
			&i.ActivityLevel,
			&i.Neutered,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPetCompatibilities = `-- name: SetPetCompatibilities :exec
DELETE FROM pet_compatibilities WHERE pet_id = $1
`

func (q *Queries) SetPetCompatibilities(ctx context.Context, petID string) error {
	_, err := q.db.ExecContext(ctx, setPetCompatibilities, petID)
	return err
}

const setPetHobbies = `-- name: SetPetHobbies :exec
DELETE FROM pet_hobbies WHERE pet_id = $1
`

func (q *Queries) SetPetHobbies(ctx context.Context, petID string) error {
	_, err := q.db.ExecContext(ctx, setPetHobbies, petID)
	return err
}

const updatePet = `-- name: UpdatePet :one
UPDATE pets
SET
  name = COALESCE($2, name),
  species_id = COALESCE($3, species_id),
  breed_id = COALESCE($4, breed_id),
  age = COALESCE($5, age),
  activity_level = COALESCE($6, activity_level),
  neutered = COALESCE($7, neutered),
  avatar_url = COALESCE($8, avatar_url)
WHERE id = $1
RETURNING id, user_id, name, species_id, breed_id, age, activity_level, neutered, avatar_url, created_at, updated_at
`

type UpdatePetParams struct {
	ID            string         `json:"id"`
	Name          sql.NullString `json:"name"`
	SpeciesID     uuid.NullUUID  `json:"species_id"`
	BreedID       uuid.NullUUID  `json:"breed_id"`
	Age           sql.NullInt32  `json:"age"`
	ActivityLevel sql.NullInt16  `json:"activity_level"`
	Neutered      sql.NullBool   `json:"neutered"`
	AvatarUrl     sql.NullString `json:"avatar_url"`
}

func (q *Queries) UpdatePet(ctx context.Context, arg UpdatePetParams) (Pet, error) {
	row := q.db.QueryRowContext(ctx, updatePet,
		arg.ID,
		arg.Name,
		arg.SpeciesID,
		arg.BreedID,
		arg.Age,
		arg.ActivityLevel,
		arg.Neutered,
		arg.AvatarUrl,
	)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.SpeciesID,
		&i.BreedID,
		&i.Age,
		&i.ActivityLevel,
		&i.Neutered,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
