// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const countMatchedUserPosts = `-- name: CountMatchedUserPosts :one
SELECT COUNT(DISTINCT posts.id) FROM posts
JOIN matches ON (
  (matches.pet_id_1 = ANY($2::uuid[]) AND posts.user_id IN (
    SELECT user_id FROM pets WHERE id = matches.pet_id_2
  )) OR
  (matches.pet_id_2 = ANY($2::uuid[]) AND posts.user_id IN (
    SELECT user_id FROM pets WHERE id = matches.pet_id_1
  ))
)
WHERE posts.user_id != $1
`

type CountMatchedUserPostsParams struct {
	UserID  string   `json:"user_id"`
	Column2 []string `json:"column_2"`
}

func (q *Queries) CountMatchedUserPosts(ctx context.Context, arg CountMatchedUserPostsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMatchedUserPosts, arg.UserID, pq.Array(arg.Column2))
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPosts = `-- name: CountPosts :one
SELECT COUNT(*) FROM posts
`

func (q *Queries) CountPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPostsAdmin = `-- name: CountPostsAdmin :one
SELECT COUNT(*) FROM posts
WHERE ($1::text IS NULL OR posts.content ILIKE '%' || $1 || '%')
  AND ($2::uuid IS NULL OR posts.user_id = $2)
`

type CountPostsAdminParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) CountPostsAdmin(ctx context.Context, arg CountPostsAdminParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPostsAdmin, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPostsCreatedAfter = `-- name: CountPostsCreatedAfter :one
SELECT COUNT(*) FROM posts WHERE created_at > $1
`

func (q *Queries) CountPostsCreatedAfter(ctx context.Context, createdAt time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPostsCreatedAfter, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchPosts = `-- name: CountSearchPosts :one
SELECT COUNT(*) FROM posts
WHERE search_vector @@ plainto_tsquery('english', $1)
`

func (q *Queries) CountSearchPosts(ctx context.Context, plaintoTsquery string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchPosts, plaintoTsquery)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (user_id, content, image_urls)
VALUES ($1, $2, $3)
RETURNING id, user_id, content, image_urls, like_count, congrats_count, funny_count, created_at, updated_at, search_vector
`

type CreatePostParams struct {
	UserID    string   `json:"user_id"`
	Content   string   `json:"content"`
	ImageUrls []string `json:"image_urls"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost, arg.UserID, arg.Content, pq.Array(arg.ImageUrls))
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		pq.Array(&i.ImageUrls),
		&i.LikeCount,
		&i.CongratsCount,
		&i.FunnyCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE id = $1 AND user_id = $2
`

type DeletePostParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeletePost(ctx context.Context, arg DeletePostParams) error {
	_, err := q.db.ExecContext(ctx, deletePost, arg.ID, arg.UserID)
	return err
}

const deletePostAdmin = `-- name: DeletePostAdmin :exec
DELETE FROM posts WHERE id = $1
`

func (q *Queries) DeletePostAdmin(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePostAdmin, id)
	return err
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, user_id, content, image_urls, like_count, congrats_count, funny_count, created_at, updated_at, search_vector FROM posts WHERE id = $1
`

func (q *Queries) GetPostByID(ctx context.Context, id string) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		pq.Array(&i.ImageUrls),
		&i.LikeCount,
		&i.CongratsCount,
		&i.FunnyCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const getReaction = `-- name: GetReaction :one
SELECT id, post_id, user_id, type, created_at FROM post_reactions WHERE post_id = $1 AND user_id = $2
`

type GetReactionParams struct {
	PostID string `json:"post_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetReaction(ctx context.Context, arg GetReactionParams) (PostReaction, error) {
	row := q.db.QueryRowContext(ctx, getReaction, arg.PostID, arg.UserID)
	var i PostReaction
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const listMatchedUserPosts = `-- name: ListMatchedUserPosts :many
SELECT DISTINCT posts.id, posts.user_id, posts.content, posts.image_urls, posts.like_count, posts.congrats_count, posts.funny_count, posts.created_at, posts.updated_at, posts.search_vector FROM posts
JOIN matches ON (
  (matches.pet_id_1 = ANY($2::uuid[]) AND posts.user_id IN (
    SELECT user_id FROM pets WHERE id = matches.pet_id_2
  )) OR
  (matches.pet_id_2 = ANY($2::uuid[]) AND posts.user_id IN (
    SELECT user_id FROM pets WHERE id = matches.pet_id_1
  ))
)
WHERE posts.user_id != $1
ORDER BY posts.created_at DESC
LIMIT $3 OFFSET $4
`

type ListMatchedUserPostsParams struct {
	UserID  string   `json:"user_id"`
	Column2 []string `json:"column_2"`
	Limit   int32    `json:"limit"`
	Offset  int32    `json:"offset"`
}

func (q *Queries) ListMatchedUserPosts(ctx context.Context, arg ListMatchedUserPostsParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listMatchedUserPosts,
		arg.UserID,
		pq.Array(arg.Column2),
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			pq.Array(&i.ImageUrls),
			&i.LikeCount,
			&i.CongratsCount,
			&i.FunnyCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPosts = `-- name: ListPosts :many
SELECT id, user_id, content, image_urls, like_count, congrats_count, funny_count, created_at, updated_at, search_vector FROM posts
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			pq.Array(&i.ImageUrls),
			&i.LikeCount,
			&i.CongratsCount,
			&i.FunnyCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsAdmin = `-- name: ListPostsAdmin :many
SELECT posts.id, posts.user_id, posts.content, posts.image_urls, posts.like_count, posts.congrats_count, posts.funny_count, posts.created_at, posts.updated_at, posts.search_vector, users.email, users.first_name, users.last_name FROM posts
JOIN users ON posts.user_id = users.id
WHERE ($1::text IS NULL OR posts.content ILIKE '%' || $1 || '%')
  AND ($2::uuid IS NULL OR posts.user_id = $2)
ORDER BY posts.created_at DESC
LIMIT $3 OFFSET $4
`

type ListPostsAdminParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListPostsAdminRow struct {
	ID            string      `json:"id"`
	UserID        string      `json:"user_id"`
	Content       string      `json:"content"`
	ImageUrls     []string    `json:"image_urls"`
	LikeCount     int32       `json:"like_count"`
	CongratsCount int32       `json:"congrats_count"`
	FunnyCount    int32       `json:"funny_count"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	SearchVector  interface{} `json:"search_vector"`
	Email         string      `json:"email"`
	FirstName     string      `json:"first_name"`
	LastName      string      `json:"last_name"`
}

func (q *Queries) ListPostsAdmin(ctx context.Context, arg ListPostsAdminParams) ([]ListPostsAdminRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostsAdmin,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsAdminRow{}
	for rows.Next() {
		var i ListPostsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			pq.Array(&i.ImageUrls),
			&i.LikeCount,
			&i.CongratsCount,
			&i.FunnyCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.Email,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByUser = `-- name: ListPostsByUser :many
SELECT id, user_id, content, image_urls, like_count, congrats_count, funny_count, created_at, updated_at, search_vector FROM posts WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListPostsByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListPostsByUser(ctx context.Context, arg ListPostsByUserParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPostsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			pq.Array(&i.ImageUrls),
			&i.LikeCount,
			&i.CongratsCount,
			&i.FunnyCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeReaction = `-- name: RemoveReaction :exec
DELETE FROM post_reactions WHERE post_id = $1 AND user_id = $2
`

type RemoveReactionParams struct {
	PostID string `json:"post_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) RemoveReaction(ctx context.Context, arg RemoveReactionParams) error {
	_, err := q.db.ExecContext(ctx, removeReaction, arg.PostID, arg.UserID)
	return err
}

const searchPosts = `-- name: SearchPosts :many
SELECT id, user_id, content, image_urls, like_count, congrats_count, funny_count, created_at, updated_at, search_vector FROM posts
WHERE search_vector @@ plainto_tsquery('english', $1)
ORDER BY ts_rank(search_vector, plainto_tsquery('english', $1)) DESC
LIMIT $2 OFFSET $3
`

type SearchPostsParams struct {
	PlaintoTsquery string `json:"plainto_tsquery"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) SearchPosts(ctx context.Context, arg SearchPostsParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, searchPosts, arg.PlaintoTsquery, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			pq.Array(&i.ImageUrls),
			&i.LikeCount,
			&i.CongratsCount,
			&i.FunnyCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setReaction = `-- name: SetReaction :one
INSERT INTO post_reactions (post_id, user_id, type)
VALUES ($1, $2, $3)
ON CONFLICT (post_id, user_id) DO UPDATE SET type = $3
RETURNING id, post_id, user_id, type, created_at
`

type SetReactionParams struct {
	PostID string `json:"post_id"`
	UserID string `json:"user_id"`
	Type   string `json:"type"`
}

func (q *Queries) SetReaction(ctx context.Context, arg SetReactionParams) (PostReaction, error) {
	row := q.db.QueryRowContext(ctx, setReaction, arg.PostID, arg.UserID, arg.Type)
	var i PostReaction
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}
