// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
	"time"
)

type Querier interface {
	AddConversationMember(ctx context.Context, arg AddConversationMemberParams) error
	CheckForMatch(ctx context.Context, swiperPetID string) (bool, error)
	Checkout(ctx context.Context, userID string) error
	CountActiveUsersAfter(ctx context.Context, createdAt time.Time) (int64, error)
	CountAllEvents(ctx context.Context) (int64, error)
	CountAllPets(ctx context.Context, dollar_1 string) (int64, error)
	CountCheckIns(ctx context.Context) (int64, error)
	CountConversationMessages(ctx context.Context, conversationID string) (int64, error)
	CountEventParticipants(ctx context.Context, eventID string) (int64, error)
	CountLocations(ctx context.Context, dollar_1 string) (int64, error)
	CountMatchedUserPosts(ctx context.Context, arg CountMatchedUserPostsParams) (int64, error)
	CountMatches(ctx context.Context) (int64, error)
	CountMatchesByUserID(ctx context.Context, userID string) (int64, error)
	CountMessages(ctx context.Context) (int64, error)
	CountPets(ctx context.Context) (int64, error)
	CountPosts(ctx context.Context) (int64, error)
	CountPostsAdmin(ctx context.Context, arg CountPostsAdminParams) (int64, error)
	CountPostsCreatedAfter(ctx context.Context, createdAt time.Time) (int64, error)
	CountSearchPosts(ctx context.Context, plaintoTsquery string) (int64, error)
	CountUpcomingEvents(ctx context.Context) (int64, error)
	CountUserConversations(ctx context.Context, userID string) (int64, error)
	CountUserMatches(ctx context.Context, userID string) (int64, error)
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CountUsersCreatedAfter(ctx context.Context, createdAt time.Time) (int64, error)
	CreateBreed(ctx context.Context, arg CreateBreedParams) (PetBreed, error)
	CreateCheckIn(ctx context.Context, arg CreateCheckInParams) (CheckIn, error)
	CreateCompatibilityOption(ctx context.Context, name string) (PetCompatibilityOption, error)
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateHobbyOption(ctx context.Context, name string) (PetHobbyOption, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateLocationCategory(ctx context.Context, name string) (LocationCategory, error)
	CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreatePet(ctx context.Context, arg CreatePetParams) (Pet, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateSpecies(ctx context.Context, name string) (PetSpecy, error)
	CreateSwipe(ctx context.Context, arg CreateSwipeParams) (Swipe, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBreed(ctx context.Context, id string) error
	DeleteCompatibilityOption(ctx context.Context, id string) error
	DeleteEvent(ctx context.Context, id string) error
	DeleteHobbyOption(ctx context.Context, id string) error
	DeleteLocation(ctx context.Context, id string) error
	DeleteLocationCategory(ctx context.Context, id string) error
	DeletePet(ctx context.Context, arg DeletePetParams) error
	DeletePost(ctx context.Context, arg DeletePostParams) error
	DeletePostAdmin(ctx context.Context, id string) error
	DeleteRefreshToken(ctx context.Context, tokenHash string) error
	DeleteSpecies(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	DeleteUserRefreshTokens(ctx context.Context, userID string) error
	GetActiveCheckIn(ctx context.Context, userID string) (CheckIn, error)
	GetActiveCheckInsByLocation(ctx context.Context, locationID string) ([]GetActiveCheckInsByLocationRow, error)
	GetAllBreeds(ctx context.Context) ([]GetAllBreedsRow, error)
	GetBreedsBySpecies(ctx context.Context, speciesID string) ([]PetBreed, error)
	GetCompatibilityOptions(ctx context.Context) ([]PetCompatibilityOption, error)
	GetConversationByID(ctx context.Context, id string) (Conversation, error)
	GetConversationMembers(ctx context.Context, conversationID string) ([]GetConversationMembersRow, error)
	GetDMConversation(ctx context.Context, arg GetDMConversationParams) (Conversation, error)
	GetEventByID(ctx context.Context, id string) (Event, error)
	GetEventParticipants(ctx context.Context, eventID string) ([]GetEventParticipantsRow, error)
	GetHobbyOptions(ctx context.Context) ([]PetHobbyOption, error)
	GetLocationByID(ctx context.Context, id string) (Location, error)
	GetLocationCategories(ctx context.Context) ([]LocationCategory, error)
	GetNearbyLocations(ctx context.Context, arg GetNearbyLocationsParams) ([]GetNearbyLocationsRow, error)
	GetPetByID(ctx context.Context, id string) (Pet, error)
	GetPetCompatibilities(ctx context.Context, petID string) ([]PetCompatibilityOption, error)
	GetPetHobbies(ctx context.Context, petID string) ([]PetHobbyOption, error)
	GetPetSwipeStats(ctx context.Context, swiperPetID string) (GetPetSwipeStatsRow, error)
	GetPostByID(ctx context.Context, id string) (Post, error)
	GetReaction(ctx context.Context, arg GetReactionParams) (PostReaction, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetSpecies(ctx context.Context) ([]PetSpecy, error)
	GetUnreadCount(ctx context.Context, arg GetUnreadCountParams) (int64, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserPostStats(ctx context.Context, userID string) (GetUserPostStatsRow, error)
	HasLikedBack(ctx context.Context, arg HasLikedBackParams) (bool, error)
	HasSwiped(ctx context.Context, arg HasSwipedParams) (bool, error)
	InsertPetCompatibility(ctx context.Context, arg InsertPetCompatibilityParams) error
	InsertPetHobby(ctx context.Context, arg InsertPetHobbyParams) error
	IsConversationMember(ctx context.Context, arg IsConversationMemberParams) (bool, error)
	IsEventParticipant(ctx context.Context, arg IsEventParticipantParams) (bool, error)
	JoinEvent(ctx context.Context, arg JoinEventParams) (EventParticipant, error)
	LeaveEvent(ctx context.Context, arg LeaveEventParams) error
	ListAllEventsAdmin(ctx context.Context, arg ListAllEventsAdminParams) ([]Event, error)
	ListAllPets(ctx context.Context, arg ListAllPetsParams) ([]Pet, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	ListLocations(ctx context.Context, arg ListLocationsParams) ([]ListLocationsRow, error)
	ListMatchedUserPosts(ctx context.Context, arg ListMatchedUserPostsParams) ([]Post, error)
	ListMatchesByPetIDs(ctx context.Context, dollar_1 []string) ([]ListMatchesByPetIDsRow, error)
	ListMatchesByUserID(ctx context.Context, arg ListMatchesByUserIDParams) ([]ListMatchesByUserIDRow, error)
	ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error)
	ListPetsByUserID(ctx context.Context, userID string) ([]Pet, error)
	ListPetsForMatching(ctx context.Context, arg ListPetsForMatchingParams) ([]Pet, error)
	ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error)
	ListPostsAdmin(ctx context.Context, arg ListPostsAdminParams) ([]ListPostsAdminRow, error)
	ListPostsByUser(ctx context.Context, arg ListPostsByUserParams) ([]Post, error)
	ListUserConversations(ctx context.Context, arg ListUserConversationsParams) ([]Conversation, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RemoveReaction(ctx context.Context, arg RemoveReactionParams) error
	SearchPosts(ctx context.Context, arg SearchPostsParams) ([]Post, error)
	SetPetCompatibilities(ctx context.Context, petID string) error
	SetPetHobbies(ctx context.Context, petID string) error
	SetReaction(ctx context.Context, arg SetReactionParams) (PostReaction, error)
	StoreRefreshToken(ctx context.Context, arg StoreRefreshTokenParams) (RefreshToken, error)
	UpdateConversationTimestamp(ctx context.Context, id string) error
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateLastReadAt(ctx context.Context, arg UpdateLastReadAtParams) error
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error)
	UpdatePet(ctx context.Context, arg UpdatePetParams) (Pet, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserBan(ctx context.Context, arg UpdateUserBanParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
}

var _ Querier = (*Queries)(nil)
