// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const countActiveUsersAfter = `-- name: CountActiveUsersAfter :one
SELECT COUNT(DISTINCT user_id) FROM post_reactions WHERE created_at > $1
`

func (q *Queries) CountActiveUsersAfter(ctx context.Context, createdAt time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveUsersAfter, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
WHERE ($1::text IS NULL OR email ILIKE '%' || $1 || '%')
  AND ($2::text IS NULL OR role = $2)
`

type CountUsersParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersCreatedAfter = `-- name: CountUsersCreatedAfter :one
SELECT COUNT(*) FROM users WHERE created_at > $1
`

func (q *Queries) CountUsersCreatedAfter(ctx context.Context, createdAt time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersCreatedAfter, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, first_name, last_name, phone, gender)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, password_hash, first_name, last_name, phone, gender, avatar_url, role, is_banned, created_at, updated_at
`

type CreateUserParams struct {
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Phone        sql.NullString `json:"phone"`
	Gender       sql.NullString `json:"gender"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.Gender,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Gender,
		&i.AvatarUrl,
		&i.Role,
		&i.IsBanned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshToken, tokenHash)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const deleteUserRefreshTokens = `-- name: DeleteUserRefreshTokens :exec
DELETE FROM refresh_tokens WHERE user_id = $1
`

func (q *Queries) DeleteUserRefreshTokens(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserRefreshTokens, userID)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token_hash, expires_at, created_at FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, first_name, last_name, phone, gender, avatar_url, role, is_banned, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Gender,
		&i.AvatarUrl,
		&i.Role,
		&i.IsBanned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, first_name, last_name, phone, gender, avatar_url, role, is_banned, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Gender,
		&i.AvatarUrl,
		&i.Role,
		&i.IsBanned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPostStats = `-- name: GetUserPostStats :one
SELECT
  COUNT(*) as total_posts,
  COALESCE(SUM(like_count), 0) as total_likes,
  COALESCE(SUM(congrats_count), 0) as total_congrats,
  COALESCE(SUM(funny_count), 0) as total_funny
FROM posts WHERE user_id = $1
`

type GetUserPostStatsRow struct {
	TotalPosts    int64       `json:"total_posts"`
	TotalLikes    interface{} `json:"total_likes"`
	TotalCongrats interface{} `json:"total_congrats"`
	TotalFunny    interface{} `json:"total_funny"`
}

func (q *Queries) GetUserPostStats(ctx context.Context, userID string) (GetUserPostStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getUserPostStats, userID)
	var i GetUserPostStatsRow
	err := row.Scan(
		&i.TotalPosts,
		&i.TotalLikes,
		&i.TotalCongrats,
		&i.TotalFunny,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, first_name, last_name, phone, gender, avatar_url, role, is_banned, created_at, updated_at FROM users
WHERE ($1::text IS NULL OR email ILIKE '%' || $1 || '%')
  AND ($2::text IS NULL OR role = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListUsersParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.Gender,
			&i.AvatarUrl,
			&i.Role,
			&i.IsBanned,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storeRefreshToken = `-- name: StoreRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, created_at
`

type StoreRefreshTokenParams struct {
	UserID    string    `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) StoreRefreshToken(ctx context.Context, arg StoreRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, storeRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  first_name = COALESCE($2, first_name),
  last_name = COALESCE($3, last_name),
  phone = COALESCE($4, phone),
  gender = COALESCE($5, gender),
  avatar_url = COALESCE($6, avatar_url)
WHERE id = $1
RETURNING id, email, password_hash, first_name, last_name, phone, gender, avatar_url, role, is_banned, created_at, updated_at
`

type UpdateUserParams struct {
	ID        string         `json:"id"`
	FirstName sql.NullString `json:"first_name"`
	LastName  sql.NullString `json:"last_name"`
	Phone     sql.NullString `json:"phone"`
	Gender    sql.NullString `json:"gender"`
	AvatarUrl sql.NullString `json:"avatar_url"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.Gender,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Gender,
		&i.AvatarUrl,
		&i.Role,
		&i.IsBanned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserBan = `-- name: UpdateUserBan :exec
UPDATE users SET is_banned = $2 WHERE id = $1
`

type UpdateUserBanParams struct {
	ID       string `json:"id"`
	IsBanned bool   `json:"is_banned"`
}

func (q *Queries) UpdateUserBan(ctx context.Context, arg UpdateUserBanParams) error {
	_, err := q.db.ExecContext(ctx, updateUserBan, arg.ID, arg.IsBanned)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users SET role = $2 WHERE id = $1
`

type UpdateUserRoleParams struct {
	ID   string `json:"id"`
	Role string `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRole, arg.ID, arg.Role)
	return err
}
